name: 'Install Godot'
description: 'Installs and sets up godot'
inputs:
    version:
        description: "Godot version number"
        default: "4.6.2"
    export_template_version:
        description: "Godot needs export templates and doesn't let you set the directory specifically, so we need this."
        default: "4.6.2.stable"
runs:
    using: "composite"
    steps:
        - name: "Create Godot Directory"
          run: mkdir godot
          shell: bash

        - name: "Download Godot"
          run: wget -q "https://downloads.godotengine.org/?version=${{ inputs.version }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64" -O godot.zip
          shell: bash

        - name: "Unzip Godot"
          run: unzip -p godot.zip > godot/godot
          shell: bash

        - name: "Download Export Templates"
          run: wget -q "https://downloads.godotengine.org/?version=${{ inputs.version }}&flavor=stable&slug=export_templates.tpz&platform=templates" -O templates.zip
          shell: bash

        - name: "Create Export Template Directory"
          run: mkdir -p ~/.local/share/godot/export_templates/${{ inputs.export_template_version }}
          shell: bash

        - name: "Unzip Export Templates"
          run: unzip -d ~/.local/share/godot/export_templates/${{ inputs.export_template_version }} templates.zip
          shell: bash

        - name: "Set Permissions"
          run: chmod +x godot/godot
          shell: bash

        - name: "Add Godot to PATH"
          run: echo "$(pwd)/godot" >> $GITHUB_PATH
          shell: bash

        - name: "New path"
          run: echo $GITHUB_PATH
          shell: bash
